FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
        python3=3.10.6-1~22.04.1 \
        python3-pip=22.0.2+dfsg-1ubuntu0.5 \
        git=1:2.34.1-1ubuntu1.12 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY app_run.patch app_entrypoint.sh ./

RUN git clone https://github.com/moevm/devops-examples && \
    mv ./devops-examples/EXAMPLE_APP/* . && \
    rm -rf devops-examples && \
    patch < app_run.patch

ENTRYPOINT [ "sh", "./app_entrypoint.sh" ]